# Generated by Django 2.1.15 on 2020-06-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('is_done', models.BooleanField()),
            ],
        ),
    ]
