# Generated by Django 2.1.15 on 2020-06-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
