name: todos of today

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploying the client and the server on AWS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        python-version: [3.7]
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node dependencies
        run: |
          cd frontend
          npm install
          cd ..
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install awscli
          pip install awsebcli
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Deploy the client to the AWS S3
        run: |
          cd frontend
          npm run build
          aws s3 sync ./dist s3://todosoftoday
          cd ..
      
      - name: Deploy the server to the AWS EB
        run: |
          cd backend
          eb deploy