name: todos of today

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploying the client and the server on AWS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        python-version: [3.7]
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node dependencies
        working-directory: ./frontend
        run: |
          npm install
      
      - name: Install Python dependencies
        working-directory: ./backend
        run: |
          pip install --upgrade pip awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Deploy the client to the AWS S3
        working-directory: ./frontend
        run: |
          npm run build 
          aws s3 sync ./dist s3://todosoftoday
      
      - name: Deploy the server to the AWS EB
        run: | 
          cd backend
          eb deploy
        